#!/usr/bin/bash
# --------------------------------------------------
# Request resources here
# --------------------------------------------------
#PBS --job-name=new_job
#PBS --output=new_job.out
#PBS --account=barberan
#PBS --mail-type=ALL
#PBS --mail-user=mtoucedasuarez@localhost
#PBS --partition=standard
#PBS --ntasks=1
#PBS --nodes=1
#PBS --mem=1gb
#PBS --time=None

# --------------------------------------------------
# Load modules here
# --------------------------------------------------

# --------------------------------------------------
# Execute commands here
# --------------------------------------------------
